local M = {}

function M.templates(paths)
  return {
    t = {
      description = 'Quick todo',
      template = '* TODO %?\n:PROPERTIES:\n:CREATED: %U\n:END:\n',
      target = paths.org_inbox,
    },
    n = {
      description = 'Next action',
      template = '* NEXT %?\n:PROPERTIES:\n:CREATED: %U\n:END:\n',
      target = paths.org_next_actions,
      headline = 'Inbox',
    },
    w = {
      description = 'Waiting for',
      template = '* WAITING %?\n:PROPERTIES:\n:CREATED: %U\n:END:\n',
      target = paths.org_waiting_for,
      headline = 'Waiting',
    },
    k = {
      description = 'Tickler / defer until',
      template = '* TODO %?\nSCHEDULED: %^T\n:PROPERTIES:\n:CREATED: %U\n:END:\n',
      target = paths.org_tickler,
      headline = 'Tickler',
    },
    j = 'Journal',
    jj = {
      description = 'Journal entry',
      template = '* %U %?\n',
      target = paths.org_journal,
      datetree = { tree_type = 'week' },
    },
    jm = {
      description = 'Morning entry',
      template = {
        '* %<%Y-%m-%d %a> 🌅 Morning',
        ':PROPERTIES:',
        ':IMPACT_TOPICS: %^{Impact topics|Health|Fitness|Self-Care|Identity|Spirituality|Hobbies|Community|Family|Friends|Partner|Dating|Tasks|Work|Education|Travel|Weather|Current Events|Money}',
        ':END:',
        '** Brain Dump',
        '%?',
        '',
        '** Intentions for Today',
        '- [ ] Main focus 1',
        '- [ ] Main focus 2',
        '- [ ] Main focus 3',
        '',
        '** Gratitude Snapshot',
        "- I'm grateful for...",
        "- I'm looking forward to...",
      },
      target = paths.org_journal,
      datetree = { tree_type = 'week' },
      properties = { empty_lines = 1 },
    },
    jd = {
      description = 'Midday check-in',
      template = {
        '* %<%Y-%m-%d %a %H:%M> ☀ Midday Check-in',
        ':PROPERTIES:',
        ':IMPACT_TOPICS: %^{Impact topics|Health|Fitness|Self-Care|Identity|Spirituality|Hobbies|Community|Family|Friends|Partner|Dating|Tasks|Work|Education|Travel|Weather|Current Events|Money}',
        ':MOOD: %^{Mood|🙂|😄|😐|😕|😣|😤|😌|🔥|💤|⚡}',
        ':END:',
        '- Current vibe:',
        "- What's flowing:",
        "- What's stuck:",
        '- One adjustment:',
        '',
        '** Thought Record (optional)',
        '| Situation | Emotion | Thought | Evidence For | Evidence Against | Reframe |',
        '|-----------+---------+---------+--------------+------------------+---------|',
        '|           |         |         |              |                  |         |',
      },
      target = paths.org_journal,
      datetree = { tree_type = 'week' },
      properties = { empty_lines = 1 },
    },
    je = {
      description = 'Evening review',
      template = {
        '* %<%Y-%m-%d %a> 🌙 Evening',
        ':PROPERTIES:',
        ':IMPACT_TOPICS: %^{Impact topics|Health|Fitness|Self-Care|Identity|Spirituality|Hobbies|Community|Family|Friends|Partner|Dating|Tasks|Work|Education|Travel|Weather|Current Events|Money}',
        ':END:',
        '** Review',
        '- Wins:',
        '- Wobbles:',
        '- Lessons:',
        '',
        '** Three Good Things',
        '1. ',
        '2. ',
        '3. ',
        '',
        '** Integration / Dialogue',
        'Me:',
        'Future Me:',
        '%?',
      },
      target = paths.org_journal,
      datetree = { tree_type = 'week' },
      properties = { empty_lines = 1 },
    },
    jv = {
      description = 'Visioning (weekly/seasonal)',
      template = {
        '* %<Week %W, %Y> 🧭 Vision Snapshot',
        ':PROPERTIES:',
        ':IMPACT_TOPICS: %^{Topics most alive this week|Health|Fitness|Self-Care|Identity|Spirituality|Hobbies|Community|Family|Friends|Partner|Dating|Tasks|Work|Education|Travel|Weather|Current Events|Money}',
        ':END:',
        '** Scene (write as if it is happening)',
        '%?',
        '',
        '** Current Mythic Arc',
        '- Archetype in play:',
        '- Theme of the chapter:',
        '- Lessons emerging:',
      },
      target = paths.org_visioning,
      datetree = { tree_type = 'week' },
      properties = { empty_lines = 1 },
    },
    r = 'Roleplay',
    rs = {
      description = 'New session',
      template = {
        '* %U -- Session with %^{Name}',
        ':PROPERTIES:',
        ':STATE: %^{State|Orientation|Attunement|Dynamic|Deep Work}',
        ':TONE: %^{Tone}',
        ':SCENE: %^{Scene Type}',
        ':END:',
        '',
        '** Intention',
        '- %?',
        '',
        '** What happened',
        '- ',
        '',
        '** Notes for next time',
        '- ',
      },
      target = paths.org_roleplay_inbox,
      headline = 'Sessions',
    },
    rp = {
      description = 'New partner',
      template = {
        '* %^{Name}',
        '',
        '** Basics',
        '- Tone together:',
        '- Current State:',
        '',
        '** Character notes',
        '- %?',
        '',
        '** Patterns noticed',
        '- ',
      },
      target = paths.org_roleplay_inbox,
      headline = 'Partners',
    },
    ri = {
      description = 'Idea / scene fragment',
      template = {
        '* %U -- %^{Title}',
        '',
        '%?',
      },
      target = paths.org_roleplay_inbox,
      headline = 'Ideas',
    },
  }
end

return M
