return {
  org_files = '~/org/**/*.org',
  org_inbox = '~/org/inbox.org',
  org_next_actions = '~/org/next-actions.org',
  org_waiting_for = '~/org/waiting-for.org',
  org_someday = '~/org/someday.org',
  org_tickler = '~/org/tickler.org',
  org_areas = '~/org/areas.org',
  org_journal = '~/org/journal.org',
  org_visioning = '~/org/visioning.org',
  org_roleplay_inbox = '~/org/roleplay/inbox.org',
  org_roam_dir = '~/org/roam',
  org_roam_journal_dir = '~/org/roam/journal',
  org_roam_notes_dir = '~/org/roam/notes',
  org_roam_people_dir = '~/org/roam/people',
  org_roam_projects_dir = '~/org/roam/projects',
  org_roam_projects_index = '~/org/roam/projects/index.org',
  org_roam_refs_dir = '~/org/roam/refs',
  denote_dir = '~/org/denote',
}
