local M = {}

function M.ensure_dirs(paths)
  vim.fn.mkdir(vim.fn.expand(paths.org_roam_dir), 'p')
  vim.fn.mkdir(vim.fn.expand(paths.org_roam_journal_dir), 'p')
  vim.fn.mkdir(vim.fn.expand(paths.org_roam_notes_dir), 'p')
  vim.fn.mkdir(vim.fn.expand(paths.org_roam_people_dir), 'p')
  vim.fn.mkdir(vim.fn.expand(paths.org_roam_projects_dir), 'p')
  vim.fn.mkdir(vim.fn.expand(paths.org_roam_refs_dir), 'p')
end

function M.templates()
  return {
    d = {
      description = 'Default note',
      target = 'notes/%<%Y%m%d%H%M%S>-%[slug].org',
      template = {
        '#+filetags: :note:',
        '',
        '%?',
      },
    },
    p = {
      description = 'Person',
      target = 'people/%[slug].org',
      template = {
        '#+filetags: :person:',
        '',
        ':PROPERTIES:',
        ':CREATED: %U',
        ':ROLE: %^{Role}',
        ':RELATIONSHIP: %^{Relationship|friend|family|partner|client|collaborator|mentor|community|other}',
        ':LAST_CONTACT: %<%Y-%m-%d>',
        ':END:',
        '',
        '* Context',
        '%?',
        '',
        '* Snapshot',
        '- Where they fit in my life/work:',
        '- What matters to them:',
        '- Current season / situation:',
        '',
        '* Conversation Threads',
        '- ',
        '',
        '* Follow-up',
        '** TODO Reach out / reply',
        '',
        '** Waiting',
        '- ',
        '',
        '* Notes',
        '',
        '* Links',
        '- Email:',
        '- Phone:',
        '- Matrix / Signal / Telegram:',
        '- Socials:',
        '',
        '* History',
        '- %U ',
      },
    },
    j = {
      description = 'Project',
      target = 'projects/%[slug].org',
      template = {
        '#+filetags: :project:',
        '',
        ':PROPERTIES:',
        ':CREATED: %U',
        ':STATUS: %^{Status|active|paused|waiting|someday|done}',
        ':AREA: %^{Area|software|infra|automation|research|learning|client}',
        ':REVIEW: %^{Review cadence|weekly|fortnightly|monthly}',
        ':REPO: %^{Repo}',
        ':PATH: %^{Local path}',
        ':STACK: %^{Stack|lua|python|typescript|go|rust|shell|mixed}',
        ':END:',
        '',
        '* Outcome',
        '%?',
        '',
        '* Problem',
        '- User / operator need:',
        '- Current pain:',
        '- Why now:',
        '',
        '* Why This Matters',
        '- ',
        '',
        '* Constraints',
        '- ',
        '',
        '* Architecture / Approach',
        '- Components:',
        '- Interfaces:',
        '- Risks:',
        '',
        '* Success Criteria',
        '- [ ] ',
        '- [ ] ',
        '- [ ] ',
        '',
        '* Next Actions',
        '** TODO First concrete step',
        '',
        '** NEXT Build / Implementation',
        '- [ ] ',
        '- [ ] ',
        '',
        '** NEXT Verification',
        '- [ ] Add or update tests',
        '- [ ] Run validation / smoke test',
        '- [ ] Check docs / UX / edge cases',
        '',
        '* Waiting / Blockers',
        '- ',
        '',
        '* Maybe / Later',
        '- ',
        '',
        '* Notes',
        '',
        '* Links',
        '- Issue:',
        '- PR:',
        '- Docs:',
        '',
        '* Decision Log',
        '- %U ',
      },
    },
    r = {
      description = 'Reference',
      target = 'refs/%<%Y%m%d%H%M%S>-%[slug].org',
      template = {
        '#+filetags: :reference:',
        '',
        ':PROPERTIES:',
        ':CREATED: %U',
        ':TYPE: %^{Type|article|repo|paper|video|podcast|docs|thread|book|tool}',
        ':SOURCE: %^{Source}',
        ':AUTHOR: %^{Author}',
        ':STATUS: %^{Status|inbox|reading|useful|archived}',
        ':END:',
        '',
        '* Summary',
        '%?',
        '',
        '* Why It Matters',
        '- ',
        '',
        '* Key Ideas',
        '- ',
        '',
        '* Quotes / Snippets',
        '- ',
        '',
        '* Relevance To My Work',
        '- Project / area:',
        '- Practical takeaway:',
        '',
        '* Actions',
        '** TODO Try / test / apply',
        '',
        '* Key Points',
        '- ',
        '',
        '* Links',
        '- URL:',
        '- Local copy:',
        '- Related project / note:',
        '',
        '* Notes',
      },
    },
  }
end

function M.dailies()
  return {
    directory = 'journal',
    templates = {
      d = {
        description = 'Daily journal',
        target = '%<%Y-%m-%d>.org',
        template = {
          '#+title: %<%A, %d %B %Y>',
          '#+filetags: Daily',
          '',
          '',
          '* %<%H:%M> %?',
        },
      },
    },
  }
end

return M
